### ISSUE TITLE
Recommend doing something when svm_load_model fails

### ISSUE THREAD

**Issue by tepperly** [febeling/rb-libsvm#21]
It seems like it would be good to either throw an exception or return nil in the event that svm_load_model(path) (libsvm.c line 500) returns NULL.

/* throw exception if svm_load_model returns NULL */
if (!model) {
  rb_raise(rb_eIOError, "Unable to read model file: %s", path);
}

The other approach would look like:

return model ? (Data_Wrap_Struct(cModel,0, model_free, model)) : Qnil;

Without any feedback from svm_load_model, Ruby segfaults when I call predict on the returned model.

Thanks,

Tom

**Comment by febeling** [comment]
Thank you for reporting this. I have set created a fix, and if it still looks right in two days I'll release it. Feel free to test and feedback in the meantime.

**Comment by febeling** [comment]
I've pushed a release, 1.4.0, to rubygems.org.
