### ISSUE TITLE
Multi Class

### ISSUE THREAD

**Issue by arjunmenon** [febeling/rb-libsvm#25]
It does not have NU_CVC and C_CVC enabled?
Returns an error.

How to enable and use it?

**Comment by febeling** [comment]
Please post 1) what you do specifically, 2) what you expect to happen, and 3) what you actually see happening.

**Comment by arjunmenon** [comment]
I was simply following the usage example and trying it out for multi class classification. So when I proceeded in the IRB like so

```
require 'libsvm'
problem = Libsvm::Problem.new

parameter = Libsvm::SvmParameter.new
parameter.cache_size = 1 # in megabytes
parameter.eps = 0.001
parameter.nu = 0.5
parameter.svm_type = Libsvm::SvmType::NU_SVC
```
It threw a name error for NU_SVC. And similarly for C_SVC, but not for others.

Specifically I was looking to perform multiclass classification of news categories.

It would be helpful if you can provide a quick example on how to perform multiclass classification. There isn't much upto date references in the internet for Ruby. 
Please.

**Comment by febeling** [comment]
I just ran that example without any name error. 
```
irb(main):010:0* parameter = Libsvm::SvmParameter.new
=> #<Libsvm::SvmParameter:0x007fca900ddd58>
irb(main):011:0> parameter.cache_size = 1 # in megabytes
=> 1
irb(main):012:0> parameter.eps = 0.001
=> 0.001
irb(main):013:0> parameter.nu = 0.5
=> 0.5
irb(main):014:0> parameter.svm_type = Libsvm::SvmType::NU_SVC
=> 1
```
Which version do you use?

**Comment by arjunmenon** [comment]
I just installed it from Ruby Gems.

**Comment by febeling** [comment]
Maybe you can run an IRB session and post the resulting output or error messages?

**Comment by arjunmenon** [comment]
Hey
Like to report correct functioning. It does not throw error for any `svm_type`!

As a quickstart, can you provide a quick snippet for Multiclass classification for text strings.

I have seen [this example](https://github.com/febeling/rb-libsvm/blob/master/examples/text.rb), if you could elaborate on the methods to add for "textual labels" and "multiple classes".

That example uses single digits as labels. So if there are multiple classes, what is the strategy?

Thanks.

**Comment by febeling** [comment]
Thanks for reporting back.

And sorry, but I can't help with ML questions that are not specific to this library. There are many sources for learning the basics of ML. There is a whole range of ways to do what you need to do.
