### ISSUE TITLE
RubyML

### ISSUE THREAD

**Issue by arbox** [febeling/rb-libsvm#26]
Dear Florian,

we've recently added `rb-libsvm` to our RubyML list: https://github.com/arbox/machine-learning-with-ruby

In order to connect all Ruby & ML related projects we introduced the `rubyml` topic on GitHub.

Please cosider adding the `rubyml` topic to this repository as well so the Ruby community can discover `rb-libsvm` faster :smiley: 

Thank you in advance!

**Comment by febeling** [comment]
Ok, makes sense. Thanks!
